# Form implementation generated from reading ui file 'boost_170_detail_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_boost170dialog(object):
    def setupUi(self, boost170dialog):
        boost170dialog.setObjectName("boost170dialog")
        boost170dialog.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        boost170dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(parent=boost170dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 381, 16))
        self.label.setObjectName("label")
        self.quit = QtWidgets.QPushButton(parent=boost170dialog)
        self.quit.setGeometry(QtCore.QRect(170, 260, 61, 24))
        self.quit.setObjectName("quit")
        self.label_2 = QtWidgets.QLabel(parent=boost170dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 381, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=boost170dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 381, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=boost170dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 381, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=boost170dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 90, 381, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=boost170dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 120, 381, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=boost170dialog)
        self.label_7.setGeometry(QtCore.QRect(10, 140, 381, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=boost170dialog)
        self.label_8.setGeometry(QtCore.QRect(10, 160, 381, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=boost170dialog)
        self.label_9.setGeometry(QtCore.QRect(10, 180, 381, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=boost170dialog)
        self.label_10.setGeometry(QtCore.QRect(10, 210, 381, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=boost170dialog)
        self.label_11.setGeometry(QtCore.QRect(10, 230, 381, 16))
        self.label_11.setObjectName("label_11")

        self.retranslateUi(boost170dialog)
        QtCore.QMetaObject.connectSlotsByName(boost170dialog)

    def retranslateUi(self, boost170dialog):
        _translate = QtCore.QCoreApplication.translate
        boost170dialog.setWindowTitle(_translate("boost170dialog", "Boost 경로 매크로 설정(VS2019) - 자세히"))
        self.label.setText(_translate("boost170dialog", "설정을 적용하면, 디폴트 $(UserRootDir) 경로인"))
        self.quit.setText(_translate("boost170dialog", "알겠어요"))
        self.label_2.setText(_translate("boost170dialog", "C:\\Users\\username\\AppData\\Local\\Microsoft\\MSBuild\\v4.0\\"))
        self.label_3.setText(_translate("boost170dialog", "경로를 만들고, 이 경로에 두 개의 파일을 생성합니다."))
        self.label_4.setText(_translate("boost170dialog", "    - Microsoft.Cpp.Win32.user.props"))
        self.label_5.setText(_translate("boost170dialog", "    - Microsoft.Cpp.x64.user.props"))
        self.label_6.setText(_translate("boost170dialog", "각 파일은 Aqua 엔진에서 자동으로 읽어들이고, 여기서 설정된"))
        self.label_7.setText(_translate("boost170dialog", "Boost 관련 경로에 대한 매크로가 생성됩니다."))
        self.label_8.setText(_translate("boost170dialog", "그래서 빌드 설정에서 Boost 경로를 엔진마다 각각 입력할 필요가"))
        self.label_9.setText(_translate("boost170dialog", "없게 되는 것입니다."))
        self.label_10.setText(_translate("boost170dialog", "각 파일의 내용은 Visual Studio에서 \'속성 관리자\'를 통해 확인할 수"))
        self.label_11.setText(_translate("boost170dialog", "있습니다."))
