# Form implementation generated from reading ui file 'boost_166_detail_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_boost166dialog(object):
    def setupUi(self, boost166dialog):
        boost166dialog.setObjectName("boost166dialog")
        boost166dialog.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        boost166dialog.resize(400, 300)
        self.label_2 = QtWidgets.QLabel(parent=boost166dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 381, 16))
        self.label_2.setObjectName("label_2")
        self.quit = QtWidgets.QPushButton(parent=boost166dialog)
        self.quit.setGeometry(QtCore.QRect(170, 260, 61, 24))
        self.quit.setObjectName("quit")
        self.label_4 = QtWidgets.QLabel(parent=boost166dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 381, 16))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(parent=boost166dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 381, 16))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(parent=boost166dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 381, 16))
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(parent=boost166dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 381, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=boost166dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 120, 381, 16))
        self.label_6.setObjectName("label_6")

        self.retranslateUi(boost166dialog)
        QtCore.QMetaObject.connectSlotsByName(boost166dialog)

    def retranslateUi(self, boost166dialog):
        _translate = QtCore.QCoreApplication.translate
        boost166dialog.setWindowTitle(_translate("boost166dialog", "Boost 경로 매크로 설정(VS2008) - 자세히"))
        self.label_2.setText(_translate("boost166dialog", "C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\ 경로에"))
        self.quit.setText(_translate("boost166dialog", "알겠어요"))
        self.label_4.setText(_translate("boost166dialog", "    - properties_win32.vsprops"))
        self.label_3.setText(_translate("boost166dialog", "파일을 생성합니다."))
        self.label.setText(_translate("boost166dialog", "설정을 적용하면, VS2008 디폴트 기준 $(VSInstallDir) 경로인"))
        self.label_5.setText(_translate("boost166dialog", "C:\\Program Files (x86) 경로에 접근하기 위해서는 관리자 권한이"))
        self.label_6.setText(_translate("boost166dialog", "필요합니다. "))
